services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: volumetrix_backend
    ports:
      - "8001:8001"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    volumes:
      - ./backend:/app
    environment:
      - HOST=0.0.0.0
      - PORT=8001

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: volumetrix_frontend
    ports:
      - "5173:5173"
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
      
  ngrok:
    image: ngrok/ngrok:latest
    restart: always
    environment:
      - NGROK_AUTHTOKEN=3F1ms9bH3O9HzXYHKWuCeSqI5dA_3jhmu13HrEAu8DLsbCzGn
    command:
      - "http"
      - "backend:8001" 
    ports:
      - "4040:4040"
    depends_on:
      - backend        